version: '3.7'

services:
  redis-master:
    image: redis:7.2-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:7.2-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6479:6379"  
    volumes:
      - "./.data:/data"

  # Instance 1
  redis-sentinel:
    restart: always
    depends_on:
      - redis-master
      - redis-slave
    build:
      context: ./sentinel
    ports:
      - "26379:26379"
    links:
      - redis-master

  # Instance 2
  redis-sentinel2:
    depends_on:
      - redis-master
      - redis-slave
    build:
      context: ./sentinel
    ports:
      - "26380:26379"
    links:
      - redis-master

  # Instance 3
  redis-sentinel3:
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26381:26379"
    build:
      context: ./sentinel
    links:
      - redis-master
  
  app1:
    depends_on:
      - redis-sentinel
      - redis-sentinel2
      - redis-sentinel3
    build:
      context: "./app"

  app2:
    depends_on:
      - redis-sentinel
      - redis-sentinel2
      - redis-sentinel3
    build:
      context: "./app"